### ISSUE TITLE
Test phpcs

### ISSUE THREAD

**Issue by va2m** [Josantonius/WP_Image#1]
Hi,
Testing using the command `composer phpcs` returned the **error code 3**.
Everything else executed OK, the problem has only with PHP Code Standards.
Why is this? Any Ideia?
Cheers!

**Comment by Josantonius** [comment]
Hi @va2m,

It's something I have to check, apparently it is generated by [WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards) when used with Composer, because when running `phpcs --standard=phpcs.xml $(find . -name '*.php');`
that error does not appear. In [Travis CI](https://travis-ci.org/Josantonius/WP_Image) either.

Regards!

**Comment by va2m** [comment]
hi @Josantonius,
I have tried `phpcs --standard=phpcs.xml $(find . -name '*.php');` and it still returns an error:
`ERROR: Referenced sniff "WordPress.Arrays.ArrayIndentation" does not exist`.  
The line of code `<rule ref="WordPress.Arrays.ArrayIndentation"/>` is present in the file `phpcs.xml` but removing it that not fix it either.
It appears that related to WordPress CS like you said.
Hope this feedback helps in anything, Cheers!

**Comment by Josantonius** [comment]
I probably fixed it locally...

We'll leave it open for now, as soon as I have a moment I'll look at it.

Sure it's helpful. 

Thank you!

**Comment by Josantonius** [comment]
This will be fixed adding the `dealerdirect/phpcodesniffer-composer-installer` [development dependency](https://github.com/Josantonius/WP_Image/blob/master/composer.json#L35).
